### ISSUE TITLE
If force flag is not set and spot price set to "" in the config cdk crashes 

### ISSUE THREAD

**Issue by SathyaBhat** [SathyaBhat/folding-aws#14]
With the spot price not set in config, and force flag not passed, cdk crashes with EOF error. 

sample config:

```
folding:
  # What AWS region do we use for VPC and ASG stacks?
  # optional
  region: eu-west-1
  # CIDR for the new vpc to be created
  # mandatory
  cidr: 10.0.0.0/16
  # What is the AMI ID of the Folding @ Home Image
  # mandatory
  ami_id: ami-0a8341e7c0a146e7f
  # What ssh key is allowed access to the instances in the ASG?
  # mandatory
  ssh_key: sathya_folding_ssh
  # What is the maximum price in USD that we're willing to pay?
  # If you leave this empty, we will fetch the current spot price
  # and raise the bid by a few cents. The instances will be set up
  # only after confirmation
  # optional
  max_spot_price: ""
  # What IP addresses to allow security group access from?
  # mandatory
  ssh_allow_ip_range: 84.232.204.212/32
  # What instance type/sizing would you prefer?
  # optional
  ec2_instance_type: "c5n.large"
  # How many instances do you wish to use?
  # optional
  asg_size: 2
  tags:
    - name: used_for
      value: folding

```

Behaviour: 

```
cdk diff -c stack_name=folding --profile sathya                                            ✘ 1 
Got spot price: 0.042000
Stack folding-vpc
There were no differences
Stack folding-asg
Security Group Changes
┌───┬──────────────────────┬─────┬──────────┬───────────────────┐
│   │ Group                │ Dir │ Protocol │ Peer              │
├───┼──────────────────────┼─────┼──────────┼───────────────────┤
│ - │ ${allow-ssh.GroupId} │ In  │ TCP 22   │ 188.26.173.155/32 │
├───┼──────────────────────┼─────┼──────────┼───────────────────┤
│ + │ ${allow-ssh.GroupId} │ In  │ TCP 22   │ 84.232.204.212/32 │
└───┴──────────────────────┴─────┴──────────┴───────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Resources
[~] AWS::EC2::SecurityGroup allow-ssh allowsshD2EB9346 
 └─ [~] SecurityGroupIngress
     └─ @@ -1,7 +1,7 @@
        [ ] [
        [ ]   {
        [-]     "CidrIp": "188.26.173.155/32",
        [-]     "Description": "from 188.26.173.155/32:22",
        [+]     "CidrIp": "84.232.204.212/32",
        [+]     "Description": "from 84.232.204.212/32:22",
        [ ]     "FromPort": 22,
        [ ]     "IpProtocol": "tcp",
        [ ]     "ToPort": 22

(cdk) ~/c/folding-aws ❯❯❯ cdk diff -c stack_name=folding --profile sathya
Got spot price: 0.042000
You have not specified a maximum price to pay for the Spot Instances.
Are you willing to pay 0.062 US Dollars / hour for each instance? Note: You have requested for 2 instances of type c5n.large.
y/N: Traceback (most recent call last):
  File "app.py", line 85, in <module>
    cdk_init(stack_name, force_spot_price)
  File "app.py", line 50, in cdk_init
    asg_stack = AsgStack(app, 
  File "/home/sathyabhat/venv/cdk/lib/python3.8/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/sathyabhat/code/folding-aws/aws_stack/asg_stack.py", line 46, in __init__
    user_consent = input("y/N: ")
EOFError: EOF when reading a line
Subprocess exited with error 1
```
